using Cookbook.Platform.Gateway.Services;
using Cookbook.Platform.Shared.Models;
using Cookbook.Platform.Shared.Models.Ingest;
using Cookbook.Platform.Storage.Repositories;

namespace Cookbook.Platform.Gateway.Endpoints;

/// <summary>
/// Recipe management endpoints.
/// </summary>
public static class RecipeEndpoints
{
    public static IEndpointRouteBuilder MapRecipeEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/recipes")
            .WithTags("Recipes");

        group.MapGet("/", SearchRecipes)
            .WithName("SearchRecipes")
            .WithSummary("Searches for recipes");

        group.MapGet("/{id}", GetRecipe)
            .WithName("GetRecipe")
            .WithSummary("Gets a recipe by ID");

        group.MapPost("/", CreateRecipe)
            .WithName("CreateRecipe")
            .WithSummary("Creates a new recipe");

        group.MapPost("/import", ImportRecipe)
            .WithName("ImportRecipe")
            .WithSummary("Imports a recipe draft from an ingest task")
            .WithDescription("Commits a reviewed recipe draft to the permanent recipe collection. " +
                           "Supports idempotency, optimistic concurrency via ETag, and duplicate detection.");

        group.MapPost("/{id}/apply-patch", ApplyPatch)
            .WithName("ApplyPatch")
            .WithSummary("Applies normalization patches to a recipe")
            .WithDescription("Applies patches generated by a normalize task to the recipe. " +
                           "Supports filtering by patch indices or maximum risk level.");

        group.MapPost("/{id}/reject-patch", RejectPatch)
            .WithName("RejectPatch")
            .WithSummary("Rejects normalization patches for a recipe")
            .WithDescription("Rejects all patches from a normalize task, leaving the recipe unchanged. " +
                           "The task is marked as Rejected.");

        return endpoints;
    }

    private static async Task<IResult> SearchRecipes(
        RecipeRepository recipeRepository,
        string? query = null,
        string? diet = null,
        string? cuisine = null,
        int limit = 10,
        CancellationToken cancellationToken = default)
    {
        var recipes = await recipeRepository.SearchAsync(query, diet, cuisine, limit, cancellationToken);
        return Results.Ok(recipes);
    }

    private static async Task<IResult> GetRecipe(
        string id,
        RecipeRepository recipeRepository,
        CancellationToken cancellationToken)
    {
        var recipe = await recipeRepository.GetByIdAsync(id, cancellationToken);
        return recipe is null ? Results.NotFound() : Results.Ok(recipe);
    }

    private static async Task<IResult> CreateRecipe(
        Recipe recipe,
        RecipeRepository recipeRepository,
        CancellationToken cancellationToken)
    {
        var created = await recipeRepository.CreateAsync(recipe, cancellationToken);
        return Results.Created($"/api/recipes/{created.Id}", created);
    }

    /// <summary>
    /// Imports a recipe draft from an ingest task, committing it to the permanent recipe collection.
    /// </summary>
    private static async Task<IResult> ImportRecipe(
        ImportRecipeRequest request,
        IRecipeImportService importService,
        CancellationToken cancellationToken)
    {
        var result = await importService.ImportAsync(request, cancellationToken);

        return result.StatusCode switch
        {
            200 => Results.Ok(result.Response),
            201 => Results.Created($"/api/recipes/{result.Response!.RecipeId}", result.Response),
            400 => Results.BadRequest(result.Error),
            404 => Results.NotFound(result.Error),
            409 => Results.Conflict(result.Error),
            410 => Results.Problem(
                statusCode: 410,
                title: "Gone",
                detail: result.Error!.Message,
                extensions: new Dictionary<string, object?>
                {
                    ["code"] = result.Error.Code,
                    ["taskId"] = result.Error.TaskId
                }),
            _ => Results.Problem(
                statusCode: result.StatusCode,
                detail: result.Error?.Message ?? "An error occurred")
        };
    }

    /// <summary>
    /// Applies normalization patches to a recipe.
    /// </summary>
    private static async Task<IResult> ApplyPatch(
        string id,
        ApplyPatchRequest request,
        IPatchApplicationService patchService,
        CancellationToken cancellationToken)
    {
        var result = await patchService.ApplyPatchAsync(id, request, cancellationToken);

        return result.StatusCode switch
        {
            200 => Results.Ok(result.Response),
            400 => Results.BadRequest(result.Error),
            404 => Results.NotFound(result.Error),
            500 => Results.Problem(
                statusCode: 500,
                title: "Internal Server Error",
                detail: result.Error?.Message ?? "An error occurred"),
            _ => Results.Problem(
                statusCode: result.StatusCode,
                detail: result.Error?.Message ?? "An error occurred")
        };
    }

    /// <summary>
    /// Rejects normalization patches for a recipe.
    /// </summary>
    private static async Task<IResult> RejectPatch(
        string id,
        RejectPatchRequest request,
        IPatchApplicationService patchService,
        CancellationToken cancellationToken)
    {
        var result = await patchService.RejectPatchAsync(id, request, cancellationToken);

        return result.StatusCode switch
        {
            200 => Results.Ok(result.Response),
            400 => Results.BadRequest(result.Error),
            404 => Results.NotFound(result.Error),
            _ => Results.Problem(
                statusCode: result.StatusCode,
                detail: result.Error?.Message ?? "An error occurred")
        };
    }
}
